//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNR8.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GNR8.Properties.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {AUTHOR}.
        /// </summary>
        internal static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {CTORBODY}.
        /// </summary>
        internal static string CTORBODY {
            get {
                return ResourceManager.GetString("CTORBODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {CTORPARAMETERS}.
        /// </summary>
        internal static string CTORPARAMETERS {
            get {
                return ResourceManager.GetString("CTORPARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {DATECREATED}.
        /// </summary>
        internal static string DATECREATED {
            get {
                return ResourceManager.GetString("DATECREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {NAMESPACE}.
        /// </summary>
        internal static string NAMESPACE {
            get {
                return ResourceManager.GetString("NAMESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {OBJECTNAME}.
        /// </summary>
        internal static string OBJECTNAME {
            get {
                return ResourceManager.GetString("OBJECTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PRIMARYKEY}.
        /// </summary>
        internal static string PRIMARYKEY {
            get {
                return ResourceManager.GetString("PRIMARYKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PROPERTIES}.
        /// </summary>
        internal static string PROPERTIES {
            get {
                return ResourceManager.GetString("PROPERTIES", resourceCulture);
            }
        }
    }
}
